In [ ]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd

import pickle as pkl



In [ ]:
with open("label_enoder_gender.pkl", "rb") as f:
    label_encoder = pkl.load(f)
with open("one_hot_encoder_geo.pkl", "rb") as f:
    geo_encoder = pkl.load(f)
with open("scaler.pkl", "rb") as f:
    scaler = pkl.load(f)

model =load_model("model.h5")


In [ ]:
# Example input data
input_data = {
     'CreditScore': 600,
     'Geography': 'France',
     'Gender': 'Male', 'Age': 40,
     'Tenure': 3, 'Balance': 60000,
     'NumOfProducts': 2,
     'HasCrCard': 1,
     'IsActiveMember': 1,
     'EstimatedSalary': 50000
     }

In [ ]:
gen_enconded = geo_encoder.transform([[input_data["Geography"]]])
gen_enconded

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [ ]:
geo_encoder.categories_[0]

array(['France', 'Germany', 'Spain'], dtype=object)

In [ ]:
geo_endoed_df= pd.DataFrame(gen_enconded, columns=geo_encoder.categories_[0])
geo_endoed_df

France  Germany  Spain
0     1.0      0.0    0.0

In [ ]:
input_data = pd.concat([pd.DataFrame([input_data]).drop("Geography", axis=1), geo_endoed_df], axis=1)
input_data

CreditScore Gender  Age  Tenure  ...  EstimatedSalary  France  Germany  Spain
0          600   Male   40       3  ...            50000     1.0      0.0    0.0

[1 rows x 12 columns]

In [ ]:
input_data["Gender"]= label_encoder.transform(input_data["Gender"])
input_data

CreditScore  Gender  Age  Tenure  ...  EstimatedSalary  France  Germany  Spain
0          600       1   40       3  ...            50000     1.0      0.0    0.0

[1 rows x 12 columns]

In [ ]:
input_data_scaled= scaler.transform(input_data)
input_data_scaled

array([[-0.52281016,  0.91241915,  0.10281024, -0.69598177, -0.26422114,
         0.80773656,  0.64609167,  0.97024255, -0.87101922,  0.99720391,
        -0.57873591, -0.57380915]])

In [ ]:
prediction = model.predict(input_data_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


In [ ]:
prediction

array([[0.02864117]], dtype=float32)

In [ ]:
prediction_prob = prediction[0][0]

In [ ]:
prediction_prob

np.float32(0.028641172)

In [ ]:
if prediction_prob>0.5:
  print("coustomer is likely to leave")
else:
  print("coustomer is not likely to leave")

coustomer is not likely to leave
